language: node_js
node_js:
  - "12"

cache:
  directories:
    - node_modules

install:
  - npm install
script:
  - echo "Salut" 
  - './node_modules/.bin/jshint ./src/'
  - './node_modules/.bin/retire'
  - if [ "$TRAVIS_BRANCH" = "master" ]; then "./node_modules/.bin/twly"; fi


# deploy:
#   provider: heroku
#   api_key:
#     secure: 
#   app: cicdtp
#   on: 
#     repo: jiangwei4/cicdTP
#     branch: dev