language: node_js
sudo: false
node_js:
  - "12"

cache:
  directories:
    - node_modules

install:
  - npm install

before_script: true

script:
  - echo "Salut" 
  - './node_modules/.bin/jshint'
  - './node_modules/.bin/retire'
  - './node_modules/.bin/twly'

after_script: true

# ./node_modules/.bin/
# deploy:
#   provider: heroku
#   api_key:
#     secure: 
#   app: cicdtp
#   on: 
#     repo: jiangwei4/cicdTP
#     branch: dev